name: Deploy Bicep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      run: |
        echo $AZURE_PASSWORD | az login -u $AZURE_USERNAME -p @STDIN

    - name: Deploy Bicep
      run: |
        az deployment group create \
          --resource-group $RESOURCE_GROUP_NAME \
          --template-file infrastructure-as-code/main.bicep \
          --parameters infrastructure-as-code/parameters.json
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
