name: Deploy Bicep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group DEV \
            --template-file infrastructure-as-code/main.bicep \
            --parameters infrastructure-as-code/parameters.json
